apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.12.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/config
        - name: pipeline-volume
          mountPath: /usr/share/logstash/pipeline
        resources:
          limits:
            cpu: 500m
            memory: 500Mi

      volumes:
      - name: config-volume
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml

      - name: pipeline-volume
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf
      
      # Setting anti-affinity to enforce that pods are placed on different nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - logstash
              topologyKey: "kubernetes.io/hostname"
            # podAffinityTerm:
            #   podSelector:
            #     matchLabels:
            #       app: logstash
            #   topologyKey: "kubernetes.io/hostname"



---
apiVersion: v1
kind: Service
metadata:
 name: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
  type: ClusterIP

